### ISSUE TITLE
Allow specifying the name of the installed Typst executable

### ISSUE THREAD

**Issue by SillyFreak** [typst-community/setup-typst#21]
this action adds `typst` to the path; for testing packages with multiple Typst versions it would be desirable that different versions could be installed under different executable names, to that in the end for example `typst` and `typst-0.10` end up on the Path.

I can imagine a few different ways this could work:
- add a parameter like `executable-name` that you could set to `typst-0.10`. If specified, the executable is renamed
- add a parameter like `use-version-suffix` that you could set to true. If true, either
  - rename the executable
  - add a symlink that uses `typst-version` for the suffix
  - add symlinks for all prefixes of the actual resolved version number, e.g. `0`, `0.10` and `0.10.0`
- always add these symlinks; they don't hurt, even if the executable is used through the name `typst`. As each invocation of `setup-typst` prepends an entry to the path, the last one will determine the version found under the name `typst`

**Comment by JamesxX** [comment]
Wouldn't mind a main build too

**Comment by SillyFreak** [comment]
you mean in addition to "latest" and version tags? and with suffix that would be `typst-main`?

**Comment by jcbhmr** [comment]
For reference (I don't know if this setup-typst currently works like this) the way this is done with other setup-node and setup-python actions is to execute the tests on each version either in parallel across multiple jobs or sequentially by re-applying setup-node again and again after each test.

Example using multiple jobs:

```yml
jobs:
  test-it:
    strategy:
      matrix:
        node-version: ["18", "20", "22"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
```

Example using multiple applications of setup-node

```yml
jobs:
  test-it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - run: npm ci
      - run: npm test
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm test
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm test
```
