### ISSUE TITLE
Use packages that are not yet published

### ISSUE THREAD

**Issue by Moelf** [typst-community/setup-typst#36]
It would be nice if setup-typst can check out a repo package.

Right now one can manually `git clone` to `~/.local/share

**Comment by yusancky** [comment]
> It would be nice if setup-typst can check out a repo package.
> 
> Right now one can manually `git clone` to `~/.local/share` but it's a bit annoying to get right on the first try

@Moelf If you mean cloning the GitHub repo where the current GitHub Actions is running, you should use [Checkout V4](https://github.com/marketplace/actions/checkout) before `setup-typst` step. It "checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it."

**Comment by yusancky** [comment]
> It would be nice if setup-typst can check out a repo package.
> 
> Right now one can manually `git clone` to `~/.local/share` but it's a bit annoying to get right on the first try

@Moelf If you mean cloning the GitHub repo where the current GitHub Actions is running, you should use [Checkout V4](https://github.com/marketplace/actions/checkout) before `setup-typst` step. It "checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it." See [Basic usage of `setup-typst`](https://github.com/typst-community/setup-typst#basic-usage) for an example.

**Comment by yusancky** [comment]
@Moelf Thank you for proposing this valuable feature suggestion! We highly appreciate your request and have started implementing this improvement. Regarding the management solution for local packages, we have developed the following design approach:

We plan to support a configuration TOML file for flexible configuration. This file will support the following fields:

For each unpublished package, users can configure its GitHub repo `<owner>/<repo>` and target (branch, tag or commit hash, default to tracking main branch), and optional package namespace/version overrides.

> [!NOTE]
> Regarding default value handling: I propose setting the default namespace to `@local`, while allowing users to globally modify this through a `default_namespace` field. The package name defaults to the GitHub repository name (removing `<owner>` prefixes). The version number will prioritize parsing semver-formatted Git tags. For non-semver tags or when using branches/commits, it will default to `0.0.0`.

Sample configuration:
```toml
[default]
namespace = "@custom"  # Global default namespace

[packages.textutils]  # Package name
git = "user/typst-textutils"
branch = "dev"  # Track development branch
version = "1.0.0"  # Explicit version specification

[packages.figure]
git = "user/typst-figures"
tag = "v2.1.0"  # Auto-extract semver version
namespace = "draft"  # Override global namespace
```

Implementation details will ensure:
- Automatic creation of Typst-compliant storage paths: `{data-dir}/typst/packages/{namespace}/{name}/{version}`
- Detailed error reporting: Terminate build with repair suggestions when essential fields are missing

We eagerly await your feedback on this design proposal. If you have additional special use cases or feature requirements, please feel free to elaborate. We will further optimize the implementation based on your suggestions.
